import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import AuthenticatedLayout from '../layout/AuthenticatedLayout';
import { ScreenColor } from '../../../styles/colors';

const Terms = () => {
    return (
        <AuthenticatedLayout title={'Term Of Use'}>
            <ScrollView style={{ backgroundColor: 'white' , marginBottom: 15}}>
                <View style={styles.centerhead}>
                    <Text style={styles.centerText}>
                        TERMS OF USE
                    </Text>
                </View>
                <View style={styles.sidehead}>
                    <Text style={styles.sideheadtext}>
                        1.	BACKGROUND
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        1.1.	This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </Text>
                    <Text style={styles.text}>
                        1.2.	This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Ownertaxi (“Application”).
                    </Text>
                    <Text style={styles.text}>
                        1.3.	This Application is owned, registered and operated by Ownertaxi (“Company”), a private limited company, incorporated under the provisions of Companies Act, 2013 and having its registered office at Solapur.
                    </Text>
                    <Text style={styles.text}>
                        1.4.	These terms of usage (“Terms of Use”) govern Your use of the Application and Services (as defined below). By using or visiting the Application, or by using any content or information provided as part of the Services on the Application, you shall be deemed to have read, understood and accepted to be bound by these Terms of Use.
                    </Text>
                    <Text style={styles.text}>
                        1.5.  For the purpose of these Terms of Use, wherever the context so requires “You”, “Your”, or “User” shall mean any natural or legal person who uses the Application for availing the Services. The term “We”, “Us”, “Our” shall mean the Company.
                    </Text>
                    <Text style={styles.text}>
                        1.6.	We reserve the right to make changes to these Terms of Use at any time. Any such modifications will become effective immediately upon posting to the Website/Application and Your continued use of the Application, and/or the Services constitutes Your agreement to such modifications. You agree to periodically review the current version of these Terms of Use as posted on the Website/Application.
                    </Text>
                </View>
                <View style={styles.sidehead}>
                    <Text style={styles.sideheadtext}>
                        2.	SERVICES
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        2.1.	The Application serves as an Application to act as a ride-hailing platform to act as a facilitator between the driver and the User (“Services”). Such Services are made available to You on the Application.
                    </Text>
                    <Text style={styles.text}>
                        2.2.	Non-identifiable information such as Gender and Age shall be shared with authorized third parties (“Third Party”) for the purpose of tailoring advertisements to target groups of people.
                    </Text>
                    <Text style={styles.text}>
                        2.3.	The User shall receive access to the contact details of the driver in order to co-ordinate pick-up locations and other information to facilitate a successful ride.
                    </Text>
                    <Text style={styles.text}>
                        2.4.	For the purpose of these Terms of Use,

                        “Applicable Law” shall mean any statute, law, regulation, ordinance, rule, judgment, notification, rule of common law, Order, decree, bye-law, government approval, directive, guideline, requirement or other governmental restriction, or any similar form of decision of, or determination by, or any interpretation, policy or administration, having the force of law of any of the foregoing, by any Authority having jurisdiction over the matter in question, whether in effect as of the date of these Terms of Use or thereafter;

                        “Authority” shall mean any national, state, provincial, local or similar government, governmental, regulatory or administrative authority, branch, agency, any statutory body or commission or any non-governmental regulatory or administrative authority, body or other organization to the extent that the rules, regulations and standards, requirements, procedures or Orders of such authority, body or other organization that have the force of Applicable Law  or any court, tribunal, arbitral or judicial body in India.

                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        3.	REPRESENTATION AND WARRANTIES
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        3.1.	Company – The Company hereby represents and warrants that –
                    </Text>
                    <Text style={styles.text}>
                        3.1.1.	We are a duly registered private company as under the relevant provisions of the Companies Act, 2013;
                    </Text>
                    <Text style={styles.text}>
                        3.1.2.	We are in compliance with the Applicable Law to provide Service, subject to these Terms of Use; and
                    </Text>
                    <Text style={styles.text}>
                        3.1.3.	We will comply with the Privacy Policy and ensure data security of the Users at all times.
                    </Text>
                    <Text style={styles.text}>
                        3.2.	User – The User hereby represents and warrants that –
                    </Text>
                    <Text style={styles.text}>
                        3.2.1.	The User is a natural or legal person, competent to contract, and has read, understood and agreed to be bound by these Terms of Use;
                    </Text>
                    <Text style={styles.text}>
                        3.2.2.	The User shall provide accurate information and details at the time of registration; and
                    </Text>
                    <Text style={styles.text}>
                        3.2.3.	The User shall not default in making payments for any Services availed through the Application.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        4.	INTELLECTUAL PROPERTY RIGHTS
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        4.1.	Copyright
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        4.1.1.	Unless otherwise stated, all Content included on the Application and made available to the Users as part of the Service, including but not limited to, trademarks, copyright, trade dress, patents, ejusdem generis, are the property of the Company, and is protected by the applicable intellectual property laws. The compilation of all Content on this Application is the exclusive property of the Company, and shall not be reproduced or used without express written permission from the Company. You agree not to decompile, reverse engineer or disassemble any Content accessible through the Application, not to insert any code or product or manipulate the Content of the Application in any way that affects the User’s experience, and not to use any data mining, data gathering or extraction method. We reserve the right to terminate our engagement and take appropriate and necessary legal action available to Us under the laws governing these Terms of Use, if We, in our sole and absolute discretion, believe that You are in violation of this clause.
                    </Text>
                    <Text style={styles.text}>
                        4.1.2.	The Content available on or via the Application, are provided to You AS IS for Your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the Company unless in a manner otherwise provided for in Clause 5 in these Terms of Use. The Company reserves all rights, not expressly granted in and to the Application.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        4.2.	Trademarks
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        www.ownertaxi.in is the domain of the Company. The Website and the Application, including, but not limited to the logo, layout, combination of colour constitute trade dress of the Company. The trademarks, domain names and trade dress of the Company shall not be used or reproduced without prior written approval from the Company, and may not be used in connection with any product or service, whether similar or not, that is not affiliated with the Company, in any manner that is likely to (a) cause confusion among Users or potential users; or (b) dilute the rights, reputation or goodwill of the Company, or (c) to disparage or discredit the Company.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        4.3.	User Generated Content
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        4.3.1.	The Application may contain various pages where You and other Users may post content and information (“User Generated Content”).
                    </Text>
                    <Text style={styles.text}>
                        4.3.2.	You may not post the following items: telephone numbers, street addresses, last names, any form of HTML or programming code, or any photographs containing nudity, or obscene, lewd, violent, harassing, sexually explicit, or otherwise objectionable subject matter. You are solely responsible for anything You may post on the Application and the consequences of posting anything on the Application.
                    </Text>
                    <Text style={styles.text}>
                        4.3.3.	You may not post or distribute content that is illegal or unlawful (including any defamatory, untrue, or obscene content or content that violates another party’s right to privacy, right against publicity or puts such party in a false light), or that violates these Terms of Use. Additionally, You may not post content with the intent to threaten the unity, integrity, security or sovereignty of India on the Website and/or the Mobile Application.
                    </Text>
                    <Text style={styles.text}>
                        4.3.4.	By posting or distributing User Generated Content to the Application, You represent and warrant that (a) You own all the rights to the User Generated Content posted by You or are authorized to use and distribute such content to the Website and/or Mobile Application and (b) such content does not and will not infringe upon any copyright or any other intellectual property right of a third party, nor violates any other rights of a third party (including a third party’s right to privacy, right against publicity or puts such party in a false light or violates any law or regulation.
                    </Text>
                    <Text style={styles.text}>
                        4.3.5.	You may not post URLs to external links that are misleading, unlawful, malicious, discriminatory or infringes/ violates someone else’s rights and/or are not directly related to the Company’s Services. You may not post unauthorized commercial communications (such as spam) on the Application. We can remove any links, content or information you post on the Application if we believe that it violates the Terms of Use or our policies in our sole and absolute discretion.
                    </Text>
                    <Text style={styles.text}>
                        4.3.6.	The Company is not responsible for, and does not endorse, content in any posting made by other Users on the Application. You are solely responsible for Your reliance on anything posted by another User on the Application. Under no circumstances shall the Company be held liable, directly or indirectly, for any loss or damage caused or alleged to have been caused to You in connection with the use of or reliance upon any content posted by another User on the Application.
                    </Text>
                    <Text style={styles.text}>
                        4.3.7.	All information, ideas, suggestions, or other communications You submit to the Company, including, but not limited to, content and information posted on the Application or communications sent via e-mail, will be on a non-confidential basis.
                    </Text>
                    <Text style={styles.text}>
                        4.3.8.	Once You submit or post content to the Application, the Company does not need to give You any further right to inspect or approve uses of such content or to compensate You for any such uses. The Company owns all right, title, and interest in any compilation, collective work or other derivative work created by the Company using or incorporating content posted by You to the Application. This shall not include identifiable information.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        5.	LIMITED PERMISSION TO COPY FROM THE APPLICATION
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        5.1.	The Company grants You permission to only access the Content made available on the Application for personal use and You agree not to, directly or indirectly, download, modify, alter, change, copy, publish, distribute or otherwise disseminate the Company’s Services, or any portion of it.
                    </Text>
                    <Text style={styles.text}>
                        5.2.	The User shall not be permitted to (i) resell or put to commercial use any information/Content made available on the Application; (ii) make any derivative use of the Application or its Content; and (iii) download or copy account information for the benefit of any third party.
                    </Text>
                    <Text style={styles.text}>
                        5.3.	You may not (whether directly or through the use of any software program) create a database in electronic or structured manual form by regularly or systematically downloading and storing all or any part of the Content/information/pages from the Application.
                    </Text>
                    <Text style={styles.text}>
                        5.4.	No part of the Application may be reproduced or transmitted to or stored in any other Application, nor shall any of its pages or part thereof be disseminated in any electronic or non-electronic form, nor included in any public or private electronic retrieval system or service without prior written permission from the Company.
                    </Text>
                </View>

                <View>
                    <Text style={styles.sideheadtext}>
                        6.	FRAUD AND IMPROPER CONDUCT
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        6.1.	You may only access the Application and use the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to Your use of the Services.
                    </Text>
                    <Text style={styles.text}>
                        6.2.	You agree that You will not in any way:
                    </Text>
                    <Text style={styles.text}>
                        6.2.1.	Interfere with the ability of others to use the Application;
                    </Text>
                    <Text style={styles.text}>
                        6.2.2.	Disrupt the normal flow of communication or otherwise act in a manner that adversely affects the other Users’ ability to use the Application;
                    </Text>
                    <Text style={styles.text}>
                        6.2.3.	Claim a relationship with or to speak for any individuals, business, association, institution, or other organization for which You are not authorized to claim such a relationship;
                    </Text>
                    <Text style={styles.text}>
                        6.2.4.	Interfere with or disrupt the Services or servers or networks connected to the Application, or disobey any requirements, procedures, policies, or regulations of networks connected to the Application;
                    </Text>
                    <Text style={styles.text}>
                        6.2.5.	Upload or post or use the Application to transfer, any content or other material that contains or constitutes viruses, trojan or other code with malicious, disruptive and/or destructive features;
                    </Text>
                    <Text style={styles.text}>
                        6.2.6.	Upload or transmit, any unlawful, harassing, libelous, abusive, threatening, harmful, vulgar, obscene, hateful, or racially, ethnically or otherwise objectionable material of any kind or nature. This includes text, graphics, video, programs or audio, URLs of external links etc., on/through the Application.
                    </Text>
                    <Text style={styles.text}>
                        6.2.7.	You shall not attempt to gain unauthorized access to any hardware or software systems or networks associated with the Application and the Services and/or Additional Services made available through the Application, or obtain any services or information not intentionally made available to You by the Company on or through the Application;
                    </Text>
                    <Text style={styles.text}>
                        6.2.8.	You shall not attempt to gain unauthorized access to the account of any other User or entity, or otherwise interfere with any other User’s or entity’s use of the Application;
                    </Text>
                    <Text style={styles.text}>
                        6.2.9.	You shall not use any false or misleading information (e.g., false or misleading names, email addresses or URLs or content or information) when using the Application, including, without limitation, with respect to any identifying information for Your account, and all information that You provide must be accurate and correct, and You must update any changes to such information, so that it remains current.
                    </Text>
                    <Text style={styles.text}>
                        6.2.10.	You will not use any communication tool or other means made available on the Application to transmit, directly or indirectly, any unsolicited bulk communications (including emails and instant messages). You may not harvest information about users of the Application for the purpose of sending or to facilitate the sending of unsolicited bulk communications. We may terminate Your access or use of the Services through the Application immediately, with or without any notice.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        7.	LIMITATION AND DISCLAIMER OF WARRANTY
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        7.1.	The Application, the Services and each portion thereof are provided “as is” without warranties of any kind either express or implied. To the fullest extent possible pursuant to applicable laws of India, We disclaim all warranties, express or implied, with respect to the Application, the Services and each portion thereof, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or other violation of rights.
                    </Text>
                    <Text style={styles.text}>
                        7.2.	The Company makes no representations or warranties of any kind, express or implied, including without limitation with respect to the fitness for consumption and/or merchantability or any other consumable or perishable product provided by the temple or third party and which may as part of the Prayer-Related Services be home-delivered to the User.
                    </Text>
                    <Text style={styles.text}>
                        7.3.	As the Company only plays the role of facilitator in the provision of Ride Hailing Services between the User and the driver, neither the Company nor its directors, officers, agents, servants and employees shall be liable for disputes arising between a driver and the User. The User agrees to release the Company from any claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of any transaction or in any other way connected with the User or any third-party temple and/or the temple’s representatives.
                    </Text>
                    <Text style={styles.text}>
                        7.4.	The Company does not warrant or make any representations regarding the use, validity, accuracy, or reliability of, or the results of the use of, or otherwise with respect to, the Applications. The Content made available on the Application is for Your general information and use only. The information/Content made available on the Application is subject to change without issuing any prior notice to You.
                    </Text>
                    <Text style={styles.text}>
                        7.5.	Under no circumstances, including, but not limited to, negligence, shall the Company be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the Application, by any person, including employees and contracted personnel of the Company.
                    </Text>
                    <Text style={styles.text}>
                        7.6.	If You are dissatisfied or harmed by the usage of the Application or anything related the Application to the extent of the Company Services or Additional Services, You may terminate these Terms of Use in accordance with Clause 9 below and such termination shall be Your sole and exclusive remedy.
                    </Text>
                    <Text style={styles.text}>
                        7.7.	The Company does not guarantee that the Services it provides will function without interruption or errors in functioning. In the particular, the operation of the Application may be interrupted due to maintenance updates, or system or network failures. In the event of interruption in provision of the Services and/or the Additional Services due to the above mentioned reasons, the Company shall inform the User of the same, and shall disclaims all liability with respect to delay in provision of Services and/or the Additional Services due to the same.
                    </Text>
                    <Text style={styles.text}>
                        7.8.	We shall be entitled to add, to vary or amend any or all these terms and conditions at any time and the User shall be bound by such addition, variation or amendment once such addition, variation or amendment is incorporated into these terms and conditions, and such amended terms and conditions are on the Application.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        8.	INDEMNIFICATION
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        You agree to indemnify, defend and hold harmless the Company, and Our affiliates, officers, directors, agents, partners, employees and representatives, from and against all losses, expenses, damages, costs, claims and demands, including reasonable attorney’s fees and related costs and expenses, due to or arising out of, (a) Your failure to comply with these Terms of Use; or (b) where any content You submit, email, or otherwise transmit to Us violates third party rights or applicable laws; or (c) any content You submit through Your use of the Services and/or Additional Services, or any portion thereof, Your connection to the Services that violates third party rights or Applicable Laws. We reserve the right, at Our own expense, to assume the exclusive defence and control of any matter otherwise subject to indemnification by You, and in such case, You agree to fully cooperate with such defence and in asserting any available defences.
                    </Text>
                </View>

                <View>
                    <Text style={styles.sideheadtext}>
                        9.	TERMINATION
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        9.1.	The Company may terminate these Terms of Use immediately without notice in the event of any breach by You of these Terms of Use or any of Our applicable policies, as posted on the Application from time to time or upon a misuse of the Services by You.
                    </Text>
                    <Text style={styles.text}>
                        9.2.	You may terminate these Terms of Use, for any or no reason, at any time, with notice to the Company pursuant to this Clause. This notice will be effective upon the Company processing Your notice.
                    </Text>
                    <Text style={styles.text}>
                        9.3.	In the event of any termination or expiration of these Terms of Use, the following sections of these Terms of Use shall survive: all provisions regarding ownership of intellectual property, indemnification, disclaimer of warranties and limitations of liability, fraud or abuse.
                    </Text>
                    <Text style={styles.text}>
                        9.4.	You agree that upon the termination of these Terms of Use, We will delete all information related to You with respect to the Services and/or Additional Services availed by You.
                    </Text>
                </View>

                <View>
                    <Text style={styles.sideheadtext}>
                        10.	SEVERABILITY
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        If any part of the Terms of Use for Services are determined to be invalid or unenforceable pursuant to applicable laws of India, including, but not limited to, the warranty, disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use for Services shall continue in effect.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        11.	GENERAL
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        Unless otherwise specified herein, these Terms of Use for Services constitute the entire agreement between You and the Company in respect of the Services and supersedes all previous written and oral agreements between You and the Company, if any. The Company’s failure to act with respect to a breach by You or others does not waive its right to act with respect to subsequent or similar breaches.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        12.	GOVERNING LAW AND DISPUTE RESOLUTION
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        These Terms of Use shall be governed by and constructed in accordance with the applicable laws of India without reference to conflict of laws principles. The courts in Delhi shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under, these Terms of Use.
                    </Text>
                </View>
                <View>
                    <Text style={styles.sideheadtext}>
                        13.	GRIEVANCE OFFICER
                    </Text>
                </View>
                <View>
                    <Text style={styles.text}>
                        In accordance with the Information Technology Act, 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:

                    </Text>
                    <Text style={styles.text}>
                        Name: Vinod
                    </Text>
                    <Text style={styles.text}>
                        E-mail Address: ownertaxi39@gmail.com
                    </Text>
                </View>

            </ScrollView >
        </AuthenticatedLayout>
    );
}

const styles = StyleSheet.create({
    text: {
        fontSize: 16,
        color: 'black',
        margin: 10,
        textAlign: 'justify'
    },
    sideheadtext: {
        fontSize: 20,
        fontWeight: '700',
        color: 'black',
        margin: 10,
    },
    sidehead: {

    },
    centerText: {
        fontSize: 24,
        fontWeight: '700',
        color: 'black',
        margin: 10,
    },
    centerhead: {
        justifyContent: 'center',
        alignItems: 'center'
    }

})

export default Terms;
